replicaCount: 1

image:
  repository: jeetkansagra07/go-web-app
  pullPolicy: IfNotPresent
  tag: "v2"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
